<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Question;

class DevelopmentQuestionsSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            [
                'question' => 'What does HTML stand for?',
                'option_a' => 'Hyper Text Markup Language',
                'option_b' => 'Home Tool Markup Language',
                'option_c' => 'Hyperlinks and Text Markup Language',
                'option_d' => 'Hyperlink Text Management Language',
                'correct' => 'A',
            ],
            [
                'question' => 'Which tag is used to create a hyperlink in HTML?',
                'option_a' => '<link>',
                'option_b' => '<a>',
                'option_c' => '<href>',
                'option_d' => '<url>',
                'correct' => 'B',
            ],
            [
                'question' => 'Which HTML attribute is used to define inline styles?',
                'option_a' => 'styles',
                'option_b' => 'class',
                'option_c' => 'font',
                'option_d' => 'style',
                'correct' => 'D',
            ],
            [
                'question' => 'What does CSS stand for?',
                'option_a' => 'Computer Style Sheets',
                'option_b' => 'Creative Style Sheets',
                'option_c' => 'Cascading Style Sheets',
                'option_d' => 'Colorful Style Sheets',
                'correct' => 'C',
            ],
            [
                'question' => 'Which property is used to change the background color in CSS?',
                'option_a' => 'background',
                'option_b' => 'bgcolor',
                'option_c' => 'color',
                'option_d' => 'background-color',
                'correct' => 'D',
            ],
            [
                'question' => 'Which CSS property controls the text size?',
                'option_a' => 'font-style',
                'option_b' => 'text-size',
                'option_c' => 'font-size',
                'option_d' => 'text-style',
                'correct' => 'C',
            ],
            [
                'question' => 'Which language runs in a web browser?',
                'option_a' => 'Java',
                'option_b' => 'C',
                'option_c' => 'Python',
                'option_d' => 'JavaScript',
                'correct' => 'D',
            ],
            [
                'question' => 'How do you write "Hello World" in an alert box in JavaScript?',
                'option_a' => 'alertBox("Hello World");',
                'option_b' => 'msg("Hello World");',
                'option_c' => 'alert("Hello World");',
                'option_d' => 'msgBox("Hello World");',
                'correct' => 'C',
            ],
            [
                'question' => 'How do you declare a JavaScript variable?',
                'option_a' => 'var carName;',
                'option_b' => 'v carName;',
                'option_c' => 'variable carName;',
                'option_d' => 'dim carName;',
                'correct' => 'A',
            ],
            [
                'question' => 'Which company developed JavaScript?',
                'option_a' => 'Mozilla',
                'option_b' => 'Microsoft',
                'option_c' => 'Sun Microsystems',
                'option_d' => 'Netscape',
                'correct' => 'D',
            ],
            [
                'question' => 'What does PHP stand for?',
                'option_a' => 'Private Home Page',
                'option_b' => 'Personal Hypertext Processor',
                'option_c' => 'PHP: Hypertext Preprocessor',
                'option_d' => 'Preprocessor Home Page',
                'correct' => 'C',
            ],
            [
                'question' => 'PHP code is executed on the ______.',
                'option_a' => 'client',
                'option_b' => 'server',
                'option_c' => 'browser',
                'option_d' => 'frontend',
                'correct' => 'B',
            ],
            [
                'question' => 'Which symbol is used to start a variable in PHP?',
                'option_a' => '&',
                'option_b' => '$',
                'option_c' => '@',
                'option_d' => '#',
                'correct' => 'B',
            ],
            [
                'question' => 'Which of the following is a PHP framework?',
                'option_a' => 'React',
                'option_b' => 'Django',
                'option_c' => 'Laravel',
                'option_d' => 'Vue.js',
                'correct' => 'C',
            ],
            [
                'question' => 'Laravel uses which template engine?',
                'option_a' => 'Twig',
                'option_b' => 'Smarty',
                'option_c' => 'Blade',
                'option_d' => 'Mustache',
                'correct' => 'C',
            ],
            [
                'question' => 'Which Artisan command is used to create a controller in Laravel?',
                'option_a' => 'php artisan make:controller',
                'option_b' => 'php make:controller',
                'option_c' => 'php artisan controller:create',
                'option_d' => 'php make controller',
                'correct' => 'A',
            ],
            [
                'question' => 'Which command runs Laravel development server?',
                'option_a' => 'php artisan run',
                'option_b' => 'php artisan server',
                'option_c' => 'php artisan serve',
                'option_d' => 'php run server',
                'correct' => 'C',
            ],
            [
                'question' => 'Which file is the entry point for a Laravel application?',
                'option_a' => 'server.php',
                'option_b' => 'index.php',
                'option_c' => 'web.php',
                'option_d' => 'routes.php',
                'correct' => 'B',
            ],
            [
                'question' => 'Which of these is a relational database?',
                'option_a' => 'MongoDB',
                'option_b' => 'Firebase',
                'option_c' => 'MySQL',
                'option_d' => 'Redis',
                'correct' => 'C',
            ],
            [
                'question' => 'Which SQL statement is used to extract data?',
                'option_a' => 'GET',
                'option_b' => 'SELECT',
                'option_c' => 'FETCH',
                'option_d' => 'EXTRACT',
                'correct' => 'B',
            ],
            [
                'question' => 'Which of the following is used for version control?',
                'option_a' => 'Docker',
                'option_b' => 'Git',
                'option_c' => 'NPM',
                'option_d' => 'Composer',
                'correct' => 'B',
            ],
            [
                'question' => 'Which command is used to initialize a Git repository?',
                'option_a' => 'git init',
                'option_b' => 'git start',
                'option_c' => 'git create',
                'option_d' => 'git begin',
                'correct' => 'A',
            ],
            [
                'question' => 'Which of the following is NOT a Git command?',
                'option_a' => 'git push',
                'option_b' => 'git commit',
                'option_c' => 'git fork',
                'option_d' => 'git clone',
                'correct' => 'C',
            ],
            [
                'question' => 'Which HTTP status code means "Not Found"?',
                'option_a' => '200',
                'option_b' => '301',
                'option_c' => '404',
                'option_d' => '500',
                'correct' => 'C',
            ],
            [
                'question' => 'What is the default port for HTTP?',
                'option_a' => '22',
                'option_b' => '80',
                'option_c' => '443',
                'option_d' => '21',
                'correct' => 'B',
            ],
            [
                'question' => 'What does API stand for?',
                'option_a' => 'Application Programming Interface',
                'option_b' => 'Advanced Programming Instruction',
                'option_c' => 'Applied Program Interface',
                'option_d' => 'Application Protocol Interface',
                'correct' => 'A',
            ],
            [
                'question' => 'Which HTML element is used for inserting a line break?',
                'option_a' => '<br>',
                'option_b' => '<lb>',
                'option_c' => '<break>',
                'option_d' => '<new>',
                'correct' => 'A',
            ],
            [
                'question' => 'Which JavaScript method is used to select an element by ID?',
                'option_a' => 'getElementByClass()',
                'option_b' => 'getElement()',
                'option_c' => 'getElementById()',
                'option_d' => 'querySelectorAll()',
                'correct' => 'C',
            ],
            [
                'question' => 'What does SQL stand for?',
                'option_a' => 'Structured Query Language',
                'option_b' => 'Simple Query Language',
                'option_c' => 'Sequential Query Language',
                'option_d' => 'Standard Query Level',
                'correct' => 'A',
            ],
        ];

        foreach ($questions as $q) {
            Question::create($q);
        }
    }
}
